### ISSUE TITLE
page numbering(?) problem

### ISSUE THREAD

**Issue by Cato-the-cat** [uclathes/uclathes#16]
On the 1st,  3rd and 4th pages of the documents (title page, abstract, dissertation committee), I get a '1' that cannot be removed. Perhaps this is a page numbering issue? It is on the bottom of p. 1, on the same line as "University of California, Los Angeles" on p.3, and on the line below "University of California, Los Angeles"  on p.4. 
The numbering is otherwise ok (Roman and Arabic numerals used correctly throughout document).

Interestingly, \usepackage{nopageno} in the preamble removes all the page numbers throughout the document, except those mysterious '1's. 

Thanks for helping.

**Comment by Cato-the-cat** [comment]
Found out what the issue is. I had forgotten to include \degreeyear{2016}

**Comment by johncolby** [comment]
Great, glad you figured it out.
