### ISSUE TITLE
Formatting Changes

### ISSUE THREAD

**Issue by odysseus9672** [uclathes/uclathes#20]
I received a couple of formatting requests from UCLA graduate division on submitting a thesis typeset with this document class. These requests seem like they will require adjustments to uclathes somewhere:

> - Do not bold your title or name on the title or abstract pages. Please remove the bold. 
> 
> - Your margins seem larger than 1". Please revise so that your margins are no larger than 1" throughout the manuscript. 
> 
> - Footnotes, bibliographic entries, long quoted passages, figure and table captions, and items in lists and tables may be single-spaced. If individual footnote or bibliographic entries are singles-paced, there must be a single blank line between entries. Please add a space between your footnote entries. Each entry may remain single-spaced.

**Comment by odysseus9672** [comment]
Looking through the file, the librarian appears to be incorrect about the margins, as set in line 125 and following of uclath12.clo:
`% DIMENSION OF TEXT:

\textheight 9in       % Height of text (including footnotes and fig-
                         % ures, excluding running head and foot).
\textwidth 6.5in         % Width of text line.`

I modified line 136 of the same file to read:
`\footnotesep 16.8pt %8.4pt    % Height of strut placed at the beginning of every`
which increased the separation between footnotes, hopefully by the correct amount.

I also modified lines 69 and 78 of uclathti.clo to read:
`         {\@titlesize \@title} \\`, and
`         {\large \@author} \\`, respectively.

This is, hopefully, sufficient to update the files for the current requirements.

**Comment by odysseus9672** [comment]
The abstract page (file uclathti.clo) also needs `\textbf` removal on lines 459 and 461:
```
         \textsc{\large Abstract of the \@Thesisname}\\[12pt]
         {\@titlesize \@title}\\[12pt]
         \normalsize \normalfont by\\[12pt]
         {\large \@author} \\
         \normalsize \normalfont
```

**Comment by odysseus9672** [comment]
This was sufficient to get the thesis accepted.

**Comment by skylian** [comment]
@odysseus9672 I have to remove \large at both title and author to get the thesis accepted. I guess there is some inconsistency among themselves.

**Comment by RyanRosario** [comment]
THANK YOU

How were you able to move the page number to be 0.75 inches away from the bottom? 

(I just had the same issue. It is appalling that the Graduate Division changes the requirements and then chooses to *not* update their manual.)

**Comment by RyanRosario** [comment]
I was also told that my margins were too large, and they would not budge. How can I get them to all be 1 inch?

**Comment by odysseus9672** [comment]
I didn't run into any issue regarding page numbering, @RyanRosario. I just checked my thesis, and the page numbering is 0.75 inches from the bottom of the page, so one of the packages you're importing might be altering that position. That, or the librarians are just wrong, like they were with the margins on mine.

**Comment by RyanRosario** [comment]
In case anyone else has this issue, I was able to get it to work by just changing

`\footskip 0.50in`
to
`\footskip 0.25in`

Hopefully they accept it this time. I will also double check my packages.

**Comment by RyanRosario** [comment]
These issues are addressed in this pull request: #21

**Comment by RyanRosario** [comment]
Hmm. In uclath17.clo line 120, `\footskip 0.25in` is not commented out:

https://github.com/uclathes/uclathes/blob/master/uclath17.clo

Are you referring to uclath*12*.clo?

**Comment by mjedmonds** [comment]
@RyanRosario Apologies, you're correct.

**Comment by johncolby** [comment]
Fixed with #21

**Comment by johncolby** [comment]
Thanks @RyanRosario @odysseus9672 @mjedmonds . Really appreciate you guys keeping things current. After we graduate, we are quickly so far removed from the process that it really wouldn't be possible to keep it current without involvement of the next generation. Congrats on filing and Go Bruins!

**Comment by vvasavada** [comment]
Hi All,

For my masters thesis submission this quarter, I had to increase footskip value to 0.75in to be accepted by Grad division. This was the notice from them:

Your page numbers should be moved a few spaces down towards the bottom of the page. Please revise.
