### ISSUE TITLE
List of figures left margin not 1 inch

### ISSUE THREAD

**Issue by mrjoshuagordon** [uclathes/uclathes#23]
Seems like it's 1.25 inches.  Grad division is asking for changes.

**Comment by RyanRosario** [comment]
Have you measured it yourself?

Double check there isn't something in your TeX that is overriding the style file.

I just measured my list of figures and it is exactly 1 inch all around.

**Comment by RyanRosario** [comment]
@mrjoshuagordon 

I found a solution:

In uclathes.cls, change

\def\l@figure{\@dottedtocline{1}{1.5em}{2.3em}}

to

\def\l@figure{\@dottedtocline{0}{0em}{2.3em}}

This shows that the analysts at Grad Division are inconsistent. I measured my list and found that mine was also 1.5in on the left margin, but they accepted it anyway.

Double-check this doesn't mess anything else up

**Comment by RyanRosario** [comment]
@jheidemann @johncolby 

This is fixed in PR #24
