### ISSUE TITLE
left and right margins are different sizes

### ISSUE THREAD

**Issue by marysame** [uclathes/uclathes#36]
The left side margin is bigger than the right side margin, but I can't find any differences in their size definitions in the uclathes.* files. I am using overleaf. Any tips how to change?

![latex_margins](https://user-images.githubusercontent.com/13440835/99200375-c4aa4d80-2759-11eb-9d2c-846fd4dcc4fa.PNG)

**Comment by adamdib** [comment]
I had a similar issue with my document, but I wasn't using Overleaf. I don't think it would be wise to try to rectify this within uclathes file, as my guess is that it's a problem with Overleaf. The way that I solved my issue was making sure that packages within my MikTex repository were updated. Best of luck!

**Comment by marysame** [comment]
Update: contacted overleaf support and they told me to put this line in main.tex after \documentclass[PhD]{uclathes}

\usepackage[letterpaper,margin=1in,footskip=0.25in]{geometry}
